### ISSUE TITLE
can't handle some characters in filename (e.g. apostrophe)

### ISSUE THREAD

**Issue by imeed166** [ijgnd/anki__pdf_viewer_with_pdfjs#3]
even though the source file match the name in the card perfectly, when i click on the link, it doesn't do anything for. I tried it with all my cards and i found that it happens to some files even though they are available in the specified folder. i don't know what causes this behavior.

**Comment by imeed166** [comment]
I'm using Anki 2.1.33

**Comment by ijgnd** [comment]
For me it works in 2.1.33 but that doesn't say much. 

I need more info.

- What does "when i click on the link, it doesn't do anything" mean exactly? Does an additional empty window open or something or is it really nothing?
- from the main window click on Help->About. In the window that opens click the "Copy Debug Info" Button and share the copied text.
- Then: disable all other add-ons, restart, and try again: does it work now?
- Have you been using this add-on for a longer time - did this add-on work before 2.1.33?
- You write "it happens to some files". So does it work for some files? If it does work for some files but not for others that's good news because it narrows down the problem. 
    - Is the problem limited to one note type or not?
    - If you have a file that does not work: Check if you have a typo or misspelling. View the html source of the field and if there's additional formatting besides the name remove it
    - Do you see some regularity - e.g. filenames that contain non-us characters break the add-on etc?
- Maybe share some screenshots or a screencast?

**Comment by imeed166** [comment]
Literally nothing happens but you were right, i tried draging the javascript into a text editor and there seems to be a problem when there is this character "'". for example : "molécule d'adhésion" doesn't work --> "javascript:pycmd("pdfjs319501851Mol%C3%A9cules d" but "Cytokines (resume).pdf" works --> "javascript:pycmd("pdfjs319501851Cytokines (resume).pdf3195018513");"

**Comment by imeed166** [comment]
"molécule d'adhésion.pdf"* sorry

**Comment by imeed166** [comment]
will there be an update to fix this problem or should i just replace this character with another? thank you very much for helping.

**Comment by ijgnd** [comment]
There will be a fix but it'll take some time because I'd like to test it first etc. but at the moment I'm busy. So you should change the filenames at the moment.

Thanks for reporting this issue.

**Comment by ijgnd** [comment]
In case you are still using Anki and are still interested in this add-on ...

I started using this add-on again and now I encode the filenames to avoid such problems.

Before I upload it to ankiweb I'm testing the new release which is available from https://github.com/ijgnd/anki__pdf_viewer_with_pdfjs/releases/download/2022-07-15/anki__pdf_viewer_with_pdfjs__2022-07-15.ankiaddon
